CineDJango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cine/', include('cine.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cine/urls.py
from django.urls import path
from . import views

app_name = 'cine'
urlpatterns = [
    path('inicio', views.index, name='index'),
    path('inicio/<str:genero>', views.indexGenero, name='index_genero'),
    path('detalles/<int:id_pelicula>', views.detalles, name='detalles'),
    path('reservas', views.reservas, name='reservas'),
    path('resumen', views.resumen, name='resumen'),
    path('getSesionesAjax/', views.getSesionesAjax, name='getSesionesAjax'),
    path('getSalasAjax/', views.getSalasAjax, name='getSalasAjax'),
    path('getEntradasAjax/', views.getEntradasAjax, name='getEntradasAjax'),
    path('saveEntradasAjax/', views.saveEntradasAjax, name='saveEntradasAjax'),
]

cine/models.py
from django.db import models

# Create your models here.

class Pelicula(models.Model):

    titulo = models.CharField(max_length=50)
    director = models.CharField(max_length=50)
    genero = models.CharField(max_length=50)
    sinopsis = models.CharField(max_length=500)
    foto = models.ImageField()

    def __str__(self):
        return u'%s' % (self.titulo)

class Sala(models.Model):

    filas = models.IntegerField()
    asientosPorFila = models.IntegerField()
    asientosUltimaFila = models.IntegerField()

    def __str__(self):
        return u'%s' % (self.id)

class Comentario(models.Model):

    tituloComentario = models.CharField(max_length=50)
    cuerpoComentario = models.CharField(max_length=250)
    pelicula = models.ForeignKey(Pelicula, on_delete = models.CASCADE)

    def __str__(self):
        return u'%s' % (self.tituloComentario)

class Visualizacion(models.Model):

    pelicula = models.ForeignKey(Pelicula, on_delete = models.CASCADE)
    sala = models.ForeignKey(Sala, on_delete = models.CASCADE)
    hora = models.DateTimeField()

    def __str__(self):
        return u'%s' % (self.hora)

class Entrada(models.Model):

    fila = models.IntegerField()
    asiento = models.IntegerField()
    visualizacion = models.ForeignKey(Visualizacion, on_delete = models.CASCADE)

    def __str__(self):
        return u'%s' % (self.id)

cine/forms.py
from django import forms

class CineForm(forms.Form):
    titulo = forms.CharField(label = "", max_length = 50, widget = forms.TextInput(attrs = {'placeholder' : 'Titulo'}))
    comentario = forms.CharField(label = "", widget = forms.Textarea(attrs={'placeholder' : 'Comentario...'}))

cine/views.py
from django.shortcuts import render
from django.utils.timezone import datetime
from .models import *
import json
from django.http import HttpResponse
from django.views.generic import TemplateView
from cine.forms import CineForm
from django.shortcuts import redirect

# Create your views here.

def index(request):

    # Se define la fecha de hoy y se filtran las peliculas
    hoy = datetime.today()
    peliculasQueMostrar = Visualizacion.objects.filter(hora__gte = hoy)
    numeroDePeliculas = peliculasQueMostrar.count()
    arrayPeliculas = []
    arrayGeneros = []

    if request.method == 'POST':
        if request.POST.get('buscar'):
            # Si se ha enviado alguna palabra para burcar, devolvemos la vista generada
            # a partir de la busqueda
            return indexBusqueda(request, request.POST.get('buscar'));
    # Se cargan todas las peliculas y generos
    for x in range(0, numeroDePeliculas):
        if not peliculasQueMostrar[x].pelicula in arrayPeliculas:
            arrayPeliculas.append(peliculasQueMostrar[x].pelicula)

    for x in range(0, numeroDePeliculas):
        if not peliculasQueMostrar[x].pelicula.genero in arrayGeneros:
            arrayGeneros.append(peliculasQueMostrar[x].pelicula.genero)

    return render(request, 'cine/index.html', {'peliculas' : arrayPeliculas, 'generos' : arrayGeneros})


def indexGenero(request, genero):

    # Se define la fecha de hoy y se filtran las peliculas
    hoy = datetime.today()
    peliculasQueMostrar = Visualizacion.objects.filter(hora__gte = hoy)
    numeroDePeliculas = peliculasQueMostrar.count()
    arrayPeliculas = []
    arrayGeneros = []
    for x in range(0, numeroDePeliculas):
        # Se aniaden solo las peliculas con el mismo genero
        if not peliculasQueMostrar[x].pelicula in arrayPeliculas:
            if peliculasQueMostrar[x].pelicula.genero == genero:
                arrayPeliculas.append(peliculasQueMostrar[x].pelicula)

    for x in range(0, numeroDePeliculas):
        if not peliculasQueMostrar[x].pelicula.genero in arrayGeneros:
            arrayGeneros.append(peliculasQueMostrar[x].pelicula.genero)

    return render(request, 'cine/index.html', {'peliculas' : arrayPeliculas, 'generos' : arrayGeneros, 'generoDePeli' : genero})


def indexBusqueda(request, buscar):

    # Se define la fecha de hoy y se filtran las peliculas
    hoy = datetime.today()
    peliculasQueMostrar = Visualizacion.objects.filter(hora__gte = hoy)
    numeroDePeliculas = peliculasQueMostrar.count()
    arrayPeliculas = []
    arrayGeneros = []
    for x in range(0, numeroDePeliculas):
        if not peliculasQueMostrar[x].pelicula in arrayPeliculas:
            # Se aniaden solo las peliculas que contengan parte del titulo
            if buscar.lower() in peliculasQueMostrar[x].pelicula.titulo.lower():
                arrayPeliculas.append(peliculasQueMostrar[x].pelicula)
            # o las peliculas que contengan parte del director
            elif buscar.lower() in peliculasQueMostrar[x].pelicula.director.lower():
                arrayPeliculas.append(peliculasQueMostrar[x].pelicula)
    for x in range(0, numeroDePeliculas):
        if not peliculasQueMostrar[x].pelicula.genero in arrayGeneros:
            arrayGeneros.append(peliculasQueMostrar[x].pelicula.genero)

    return render(request, 'cine/index.html', {'peliculas' : arrayPeliculas, 'generos' : arrayGeneros})


def detalles(request, id_pelicula):

    hoy = datetime.today()
    pelicula = Pelicula.objects.get(id = id_pelicula)
    visualizacionesConPelicula = Visualizacion.objects.filter(pelicula = id_pelicula).filter(hora__gte = hoy)
    comentarios = Comentario.objects.filter(pelicula = pelicula).all()

    if request.method == 'POST':
        form = CineForm(request.POST)
        if form.is_valid():

            titulo = form.cleaned_data['titulo']
            comentario = form.cleaned_data['comentario']

            nuevoComentario = Comentario(tituloComentario = titulo, cuerpoComentario = comentario, pelicula = pelicula)
            nuevoComentario.save()

            request.method = 'GET'
            return detalles(request, id_pelicula)
    else:
        form = CineForm()

    return render(request, 'cine/detalles.html', {'pelicula' : pelicula, 'sesiones' : visualizacionesConPelicula, 'comentarios' : comentarios, 'form' : form})


def reservas(request):

    # Se define la fecha de hoy y se filtran las peliculas
    hoy = datetime.today()
    visualizacionesQueMostrar = Visualizacion.objects.filter(hora__gte = hoy)
    numeroDePeliculas = visualizacionesQueMostrar.count()
    arrayPeliculas = []
    for x in range(0, numeroDePeliculas):
        if not visualizacionesQueMostrar[x].pelicula in arrayPeliculas:
            arrayPeliculas.append(visualizacionesQueMostrar[x].pelicula)

    return render(request, 'cine/reservas.html', {'peliculas' : arrayPeliculas, 'visualizaciones' : visualizacionesQueMostrar})


def getSesionesAjax(request):

    idPelicula = request.GET.get('idPelicula', 1)
    sesiones_set = []
    todasLasSesiones = []

    visualizacionesConPelicula = Visualizacion.objects.filter(pelicula = idPelicula)

    numeroDeSesiones = visualizacionesConPelicula.count()
    for x in range(0, numeroDeSesiones):
        todasLasSesiones.append(visualizacionesConPelicula[x])

    for sesion in todasLasSesiones:
        sesiones_set.append({'sesion': sesion.hora.strftime("%m/%d %H:%M"), 'idVisualizacion' : sesion.id, 'sala' : sesion.sala.id})

    return HttpResponse(json.dumps(sesiones_set), content_type='application/json')


def getSalasAjax(request):

    idSala = request.GET.get('idSala', 1)
    sala = Sala.objects.get(id = idSala)
    sala_set = []

    sala_set.append({'idSala' : sala.id , 'filas' : sala.filas, 'asientosPorFila' : sala.asientosPorFila, 'asientosUltimaFila' : sala.asientosUltimaFila})

    return HttpResponse(json.dumps(sala_set), content_type='application/json')

def getEntradasAjax(request):
    idVisualizacion = request.GET.get('idVisualizacion', 1)
    visualizacion = Visualizacion.objects.filter(id = idVisualizacion).get()
    entrada_set = visualizacion.entrada_set.all()
    entradas = []
    for entrada in entrada_set:
        entradas.append({'fila' : entrada.fila, 'asiento' : entrada.asiento})

    return HttpResponse(json.dumps(entradas), content_type='application/json')


def saveEntradasAjax(request):
    entradas = request.GET.getlist('arrayEntradas[]')

    for entrada in entradas:
        # Preparamos las variables para la entrada
        repEntrada = entrada.split(".")
        idSesion = repEntrada[0]
        fila = repEntrada[1]
        asiento = repEntrada[2]

        visualizacion = Visualizacion.objects.filter(id = idSesion).get()
        nuevaEntrada = Entrada(fila = fila, asiento = asiento, visualizacion = visualizacion)
        nuevaEntrada.save()

    return redirect('../reservas')


def resumen(request):
    if request.method == 'POST':
        entradasReservadas = []
        checkBoxes = request.POST.getlist('checks[]')

        for entrada in checkBoxes:
            print('entrada:' ,entrada)
            # Preparamos las variables para la entrada
            repEntrada = entrada.split(",")
            idSesion = repEntrada[0]
            fila = repEntrada[1]
            asiento = repEntrada[2]

            visualizacion = Visualizacion.objects.filter(id = idSesion).get()
            nuevaEntrada = Entrada(fila = fila, asiento = asiento, visualizacion = visualizacion)
            nuevaEntrada.save()
            entradasReservadas.append(nuevaEntrada)

    return render(request, 'cine/resumen.html', {'entradas' : entradasReservadas})

cine/templates/cine/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">

    <title>Cine</title>

    {% block scripts %}

    	<link rel="stylesheet" href="{% static "cine/css/mainStyle.css" %}" />
    	<link rel="stylesheet" href="{% static "cine/css/fonAwesome.css" %}">
      <link rel="stylesheet" href="{% static "cine/css/w3.css" %}">
    	<link rel='stylesheet' href="{% static "cine/css/w3.css" %}" >

      <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
      <script src="{% static "cine/js/cineScript.js" %}"></script>
    {% endblock %}

  </head>
  <body>
    <!-- Cabecera de la pagina -->
    <header>
      <nav>
    		<div class="sticky top_menu">
    			<div class="top">
    				<img src="{% static "cine/images/logo.png"%}" alt="logo"/>
    			</div>
    			<ul>
    				<li class="left"><a class="" href="{% url 'cine:index'%}">Home</a></li>
    				<li class="left"><a class="" href="{% url 'cine:reservas'%}">Reservas</a></li>
    			</ul>
    		</div>

    	</nav>
    </header>
    {% block contenido %}
    {% endblock %}
  </body>
</html>

cine/templates/cine/detalles.html
{% extends "./base.html"%}

{% block contenido %}
<div class="cont">
  <div class="left">
    <img class="cartelGrande" src="{{ pelicula.foto.url }}" alt="{{ pelicula.titulo }}">
  </div>
  <div class="left descripcion">
    <p><span class="tituloStyle">Titulo : </span>{{ pelicula.titulo }}</p>
    <p><span class="tituloStyle">Director : </span>{{ pelicula.director }}</p>
    <p><span class="tituloStyle">Genero : </span>{{ pelicula.genero }}</p>
    <p><span class="tituloStyle">Sinopsis: </span></p>
    <p>{{ pelicula.sinopsis }}</p>
  </div>
  <div class="left">
    <h5 class="tituloStyle">Proximas sesiones:</h5>
    <ul class="comentarios">
      {% for sesion in sesiones%}
      <li class="comentario">{{sesion.hora}}</li>
      {% endfor %}
    </ul>

  </div>
  <div class="clear cont filtro">
    <h3 class="margenTop tituloStyle">Comentarios:</h3>
    <ul class="comentarios">
      {% for comentario in comentarios%}
      <li class="comentario">
        <header class="tituloComentario">
          <span class="bold">{{comentario.tituloComentario}}</span>
        </header>
        <div class="cuerpoComentario margen">
          <p>{{comentario.cuerpoComentario}}</p>
        </div>
      </li>
      {% endfor %}
    </ul>
    <div class="margenTop">
      <h4 class="tituloStyle">¡Añade tu comentario!</h3>
      <form class="nuevoComentario" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Comentar">
      </form>
    </div>

  </div>
</div>



{% endblock %}

cine/templates/cine/index.html
{% extends "./base.html"%}

{% block contenido %}
  <div class="cont">
    <h1>Películas
      {% if generoDePeli %}
        de {{ generoDePeli }}
      {% endif %}
    </h1>
      {% if peliculas%}
        <div class="filtro">
          <div class="opciones">
            <select class="navPeliculas" name="Genero">
              <option value="" disabled selected>Filtrar género</option>
              {% for genero in generos %}
                <option url="{% url 'cine:index_genero' genero=genero %}" value="{{ genero }}">{{ genero }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="opciones">
            <form class="navPeliculas" action="{% url 'cine:index' %}" method="post">
              {% csrf_token %}
              <input type="text" name="buscar" placeholder="Buscar pelicula...">
              <button type="submit"> <i class="fa fa-search">Buscar</i> </button>
            </form>
          </div>

        </div>


        {% for pelicula in peliculas %}
        <div class="peliculaInicio">
          {% include "./pelicula.html"%}
        </div>
        {% endfor %}

      {% else %}
        <p>En este momento no hay peliculas con sesiones o con ese criterio de busqueda.</p>
      {% endif %}
  </div>


{% endblock %}

cine/templates/cine/pelicula.html
<article class="cine" genero="{{ pelicula.genero }}">
  <a class="cartelEnlace" href="{% url 'cine:detalles' id_pelicula=pelicula.id %} ">
    <img class="cartel" src="{{ pelicula.foto.url }}" alt="{{ pelicula.titulo }}">
    <h4>{{ pelicula.titulo }}</h4>
    <h6>{{ pelicula.director }}</h6>
  </a>
</article>

cine/templates/cine/reservas.html
{% extends "./base.html"%}

{% block contenido %}

{% if peliculas%}
  <!--
  Select con las peliculas
  <select onchange="" class="selectPelicula" name="peliculas">
    <option value="" disabled selected>Seleccina pelicula</option>
    {% for pelicula in peliculas %}
    <option value="{{ pelicula.id }}">{{ pelicula.titulo }}</option>
    {% endfor %}
  </select>
  Select con las sesiones cargadas dinamicamente
  <select onchange="" class="selectSesion" name="sesion">
    <option value="" disabled selected>Seleccina sesion</option>
  </select>
-->
  <!-- Indicador con la sala de esa sesion -->
  <div class="reservas">


  <form class="navPeliculas" action="resumen" method="post">
    {% csrf_token %}
    <button type="submit" class="reservar" name="reservar">Reservar asientos</button>
    <div class="visualizaciones">
      {% for visualizacion in visualizaciones %}
        <div class="visualizacion">

          <button class="noRef colapsar" onclick="cargarSala({{ visualizacion.sala.filas }},
          {{ visualizacion.sala.asientosPorFila }},
          {{ visualizacion.sala.asientosUltimaFila }},
          {{ visualizacion.id }})"> Película: {{ visualizacion.pelicula.titulo }} || Sala: {{ visualizacion.sala.id }} || Hora : {{ visualizacion.hora }}</button>

          <div class="vis{{ visualizacion.id }}Sala contenidoSala">
          </div>
        </div>
      {% endfor %}
    </div>
  </form>
</div>

{% endif %}

{% endblock %}

cine/templates/cine/resumen.html
{% extends "./base.html"%}

{% block contenido %}
<div class="cont">
  <h2 class="tituloStyle">Gracias por tu reserva!</h2>
  <h4 class="tituloStyle">Aqui tienes tus entradas:</h4>
  {% for entrada in entradas%}
    <div class="clear entrada">
      <div class="left">
        <img class="cartelPequenio" src="{{ entrada.visualizacion.pelicula.foto.url }}" alt="{{ entrada.visualizacion.pelicula.titulo }}">
      </div>
      <div class="left descripcion">
        <p><span class="tituloStyle">Sesion: </span>{{ entrada.visualizacion.hora }}</p>
        <p><span class="tituloStyle">Sala : </span>{{ entrada.visualizacion.sala.id }}</p>
        <p><span class="tituloStyle">Fila : </span>{{ entrada.fila }} <span class="tituloStyle"> Asiento : </span>{{ entrada.asiento }}</p>
      </div>
    </div>
    <br/>
  {% endfor %}
</div>
{% endblock %}